### ISSUE TITLE
Default settings feature request

### ISSUE THREAD

**Issue by deftesthawk** [BlueStaggo/moderner-beta#17]
Could you add default config files for the following:

- World Preset
- Chunk Provider
- Biome Provider
- Cave Biome Provider

This would allow modpack creators to configure the default world settings for their modpack, which would compliment the [Default World Type](https://www.curseforge.com/minecraft/mc-mods/defaultworldtype) mod and It would also allow regular players to keep generating new worlds without having to copy and paste the settings into it every time. 

Thank you for reading :)

**Comment by blood-heaven** [comment]
I just found out about this method, copy and paste it properly or you'll mess things up:

Create a Datapack and create following folders 

Datapack\data\moderner_beta\worldgen\world_preset

In the "world_preset" folder you will need to create a file named "moderner_beta.json"

and put this code inside of it [https://pastebin.com/wwBe1gvw](url)

If you wish to change the generation you need to change the "provider_settings"

"cave_provider_settings" --> Paste your Cave Biome Provider Code under this section
"provider_settings" --> Paste your Biome Provider Code under this section
"provider_settings" --> Paste your Chunk Provider Code under this section

Dont mess up the order, it starts with Cave Biome Provider then Biome Provider Code and lastly Chunk Provider.

If you have done everything correctly and you try to change the World Preset it will state Custom instead of Beta 1.7.3.

I have made an template Datapack, it uses the Beta Vanilla Preset feel free to use it.

[Modern Beta Custom World Preset.zip](https://github.com/user-attachments/files/17087841/Modern.Beta.Custom.World.Preset.zip)

**Comment by deftesthawk** [comment]
Yeah I already had the Default World Type Mod working as I did a little digging in the mods code to figure it out. The rest is really helpful, I just setup the Global Packs Mod and it's working great with the 

> Modern Beta Custom World Preset.zip

You provided, now I know everything is working I'll have a go at creating my own custom settings. Thanks for the help, I greatly appreciate it :)

**Comment by FireController1847** [comment]
Hey there! I hate to bump an old issue, but I've been having issues with this solution. I'm finding that, using the latest Fabric 1.21.4 version, if I copy in the values for the 1.12.2 generation preset, it proves to give completely different generation than if I manually select the preset. I've used the datapack method, and it's seeming like it's giving consistent results of basically corrupted worlds (biomes with no trees, odd animal generation, etc).

Any thoughts? @BlueStaggo
