### ISSUE TITLE
Crash with Create and JEI on Forge

### ISSUE THREAD

**Issue by FranticFairy** [BlueStaggo/moderner-beta#6]
Minecraft Version: 1.20.1, Forge 47.3.5, running only Moderner Beta, JEI, Create and their dependencies.

So long as Moderner Beta is installed - even outside of Moderner Beta worlds - using JEI's recipe viewer to view a Create Bulk Washing recipe hard-crashes the game. Reporting it here since the crash report mentions Moderner Beta specifically, and because removing Moderner Beta solves the issue.

Crash Log attached.

[crash-2024-07-16_11.03.33-client.txt](https://github.com/user-attachments/files/16246275/crash-2024-07-16_11.03.33-client.txt)

**Comment by TalonFloof** [comment]
Can confirm

A similar issue occurs with EMI, thought instead of crashing, it says, "Render Error" and gives the same error in the console as seen in the crash log above.

**Comment by PGtheVRguy** [comment]
Im running a fabric modpack with a Modern Beta worldgen mod, Create, and JEI and it auto crsashes when viewing bulk washing

**Comment by germe-deb** [comment]
the fix for this should be setting a position, because the crash happens because there is apparently no position in the water block create puts on the widget for jei/rei/emi
I don't know programming, but I think that's the solution.
The problem also happens to me with fabric, create, emi and moderner beta installed and it's pretty annoying

The Pos (position of the water) could be set to the player's position, or some random block in the world, or even 0, 0, 0.
The mod could also set the color for that without the need for a world position

That are my possible fixes, I hope this gets fixed soon!!!

**Comment by forkiesassds** [comment]
The bug has been fixed in the next upcoming release of the mod.

**Comment by PGtheVRguy** [comment]
Awesome! Tysm!!

**Comment by TalonFloof** [comment]
Sweet, glad to hear it's been fixed ^w^
